# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.3
PKG_RELEASE:=20211015
META_TITLE:=Jellyfin
META_DEPENDS:=+luci-app-jellyfin +luci-i18n-jellyfin-zh-cn
META_DESCRIPTION:=Jellyfin是一个免费自由的媒体系统软件，可以让您方便地管理和串流您的媒体。 
META_AUTHOR:=Jellyfin
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/jellyfin
META_WEBSITE:=https://jellyfin.org

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
