# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221106
META_TITLE:=LANraragi电子书
META_TITLE.en:=LANraragi
META_DEPENDS:=+luci-app-lanraragi +luci-i18n-lanraragi-zh-cn +docker-deps
META_DESCRIPTION:=LANraragi是一个开源的电子书、漫画管理平台。
META_DESCRIPTION.en:=LANraragi is an open source e-book and comic management platform.
META_AUTHOR:=LANraragi
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/lanraragi
META_WEBSITE:=https://lrr.tvc-16.science/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
