# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2
PKG_RELEASE:=20240313
META_TITLE:=TypeCho博客
META_TITLE.en:=TypeCho
META_DEPENDS:=+luci-app-typecho +luci-i18n-typecho-zh-cn +docker-deps
META_DESCRIPTION:=TypeCho 是一个轻量级博客。
META_DESCRIPTION.en:=TypeCho is a lightweight blog.
META_AUTHOR:=TypeCho
META_TAGS:=net
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/typecho
META_WEBSITE:=https://typecho.org/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
