# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2
PKG_RELEASE:=20230619
META_TITLE:=HTReader在线读书
META_TITLE.en:=HTReader
META_DEPENDS:=+luci-app-htreader +luci-i18n-htreader-zh-cn +docker-deps
META_DESCRIPTION:=HTReader 是一个网页版本在线读书。
META_DESCRIPTION.en:=HTReader is book reader in web.
META_AUTHOR:=hectorqin
META_TAGS:=net
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/htreader
META_WEBSITE:=https://github.com/hectorqin/reader
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
