# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=Go-WebDAV
META_DEPENDS:=+gowebdav +luci-i18n-gowebdav-zh-cn +luci-app-gowebdav
META_DESCRIPTION:=OpenWrt-WebDAV服务端，可为OpenWrt开启WebDav服务。
META_AUTHOR:=CN_SZTL/1715173329
META_ARCH:=x86_64 aarch64_cortex-a53
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/nas/gowebdav
META_WEBSITE:=https://github.com/1715173329/gowebdav

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
