# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221212
META_TITLE:=Excalidraw画板
META_TITLE.en:=Excalidraw
META_DEPENDS:=+luci-app-excalidraw +luci-i18n-excalidraw-zh-cn +docker-deps
META_DESCRIPTION:=Excalidraw是支持多人协同的私有化在线画板工具。
META_DESCRIPTION.en:=Excalidraw is a privatized online drawing board tool that supports multi-person collaboration.
META_AUTHOR:=excalidraw
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/excalidraw
META_WEBSITE:=https://excalidraw.com/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
