# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=FTP服务器
META_DEPENDS:=+vsftpd-alt +luci-app-vsftpd +luci-i18n-vsftpd-zh-cn
META_DESCRIPTION:=一个完全免费的、开放源代码的ftp服务器软件
META_AUTHOR:=Cezary Jackiewicz
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/nas/vsftpd
META_WEBSITE:=http://vsftpd.beasts.org/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
