# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.6
PKG_RELEASE:=20250406
META_TITLE:=1Panel
META_TITLE.en:=1Panel
META_DEPENDS:=+luci-app-istorepanel +luci-i18n-istorepanel-zh-cn +docker-deps
META_DESCRIPTION:=1Panel 是新一代的 Linux 服务器运维管理面板
META_DESCRIPTION.en:=1Panel is the new generation Linux server maintenance panel.
META_AUTHOR:=FIT2CLOUD
META_TAGS:=net
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/istorepanel
META_WEBSITE:=https://1panel.cn/index.html
META_TUTORIAL:=https://doc.linkease.com/zh/guide/istore/software/istorepanel.html

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
