# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.10
PKG_RELEASE:=20250328
META_TITLE:=系统便利工具
META_TITLE.en:=SysTools
META_DEPENDS:=+luci-app-systools +luci-i18n-systools-zh-cn
META_DESCRIPTION:=一些便利的工具集，方便修复一些问题，一键开关 IPv6。
META_DESCRIPTION.en:=Some convenient tools which can fix some errors, switch IPv6.
META_AUTHOR:=xiaobao
META_TAGS:=system tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/system/systools/pages
META_WEBSITE:=https://github.com/istoreos

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
