# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.1.0
PKG_RELEASE:=1
META_TITLE:=Zerotier
META_DEPENDS:=+zerotier +luci-app-zerotier +luci-i18n-zerotier-zh-cn
META_DESCRIPTION:=非常简单易用的内网穿透工具，能实现虚拟局域网的组建。
META_DESCRIPTION.en:=A smart ethernet switch for earth
META_AUTHOR:=zerotier
META_TAGS:=networking service
META_LUCI_ENTRY:=/cgi-bin/luci/admin/vpn/zerotier
META_WEBSITE:=https://www.zerotier.com/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
