# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.2.0
PKG_RELEASE:=1
META_TITLE:=奇游联机宝加速器
META_DEPENDS:=+qiyougamebooster +luci-i18n-qiyougamebooster-zh-cn +luci-app-qiyougamebooster
META_DESCRIPTION:=付费游戏加速器 (开启服务后，使用联机宝APP绑定路由器并指定加速主机)。
META_AUTHOR:=奇游
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/qiyougamebooster
META_WEBSITE:=https://www.qiyou.cn/
META_ARCH:=all

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
