# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.3.1
PKG_RELEASE:=3
META_TITLE:=SunPanel导航页
META_TITLE.en:=SunPanel navigation panel
META_DEPENDS:=+luci-i18n-sunpanel-zh-cn +sunpanel +luci-app-sunpanel
META_DESCRIPTION:=一个易用好看的NAS导航页。
META_DESCRIPTION.en:=Server, NAS navigation panel, Homepage, Browser homepage.
META_AUTHOR:=hslr-s/sun-panel
META_ARCH:=x86_64 aarch64_cortex-a53
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/sunpanel
META_WEBSITE:=https://sun-panel-doc.enianteam.com

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature