# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=20200824
PKG_RELEASE:=5
META_TITLE:=Socat
META_DEPENDS:=+luci-app-socat +luci-i18n-socat-zh-cn
META_DESCRIPTION:=Socat 是 Linux 下的一个多功能的网络工具，名字来由是「Socket CAT」。其功能与有瑞士军刀之称的 Netcat 类似，可以看做是 Netcat 的加强版。
META_AUTHOR:=Lienol <lawlienol@gmail.com>
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/network/socat
META_WEBSITE:=https://github.com/Lienol/openwrt-package/tree/main/luci-app-socat

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
