# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=unblockmusic
META_DEPENDS:=+node +UnblockNeteaseMusic +UnblockNeteaseMusic-Go +luci-i18n-unblockmusic +luci-app-unblockmusic
META_DESCRIPTION:=解锁网易云音乐客户端变灰歌曲。
META_AUTHOR:=Tianling Shen
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/unblockmusic
META_WEBSITE:=https://github.com/1715173329/UnblockNeteaseMusic

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
