# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221114
META_TITLE:=Navidrome音乐
META_TITLE.en:=Navidrome
META_DEPENDS:=+luci-app-navidrome +luci-i18n-navidrome-zh-cn +docker-deps
META_DESCRIPTION:=Navidrome是开源音乐服务器，自建云端音乐播放器。
META_DESCRIPTION.en:=Navidrome is an open source music server with a self-built cloud music player.
META_AUTHOR:=Navidrome
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/navidrome
META_WEBSITE:=https://github.com/navidrome/navidrome
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
