# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.13
PKG_RELEASE:=20221214
META_TITLE:=AirConnect
META_DEPENDS:=+airconnect +luci-app-airconnect +luci-i18n-airconnect-zh-cn
META_DESCRIPTION:=让 UPnP/Sonos 和 Chromecast 设备支持 AirPlay 音频串流
META_DESCRIPTION.en:=Use AirPlay to stream to UPnP/Sonos &amp; Chromecast devices
META_AUTHOR:=philippe44
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/airconnect
META_WEBSITE:=https://github.com/philippe44/AirConnect

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
