# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.5
PKG_RELEASE:=20220426
META_TITLE:=定时设置
META_DEPENDS:=+luci-app-autotimeset +luci-i18n-autotimeset-zh-cn
META_DESCRIPTION:=定时设置包括：定时重启、定时关机、定时重启网络
META_AUTHOR:=SirPdboy
META_TAGS:=system tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/system/autotimeset
META_WEBSITE:=https://github.com/sirpdboy/luci-app-autotimeset

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
