# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.3.17
PKG_RELEASE:=20231208
META_TITLE:=驿站 - 边缘计算
META_DEPENDS:=+owxbyz
META_DESCRIPTION:=驿站 - 租用闲置设备资源，躺赚积分收益。影视VIP、音乐VIP、话费随心兑换。【玩物科技出品】
META_AUTHOR:=玩物科技
META_TAGS:=net tool
META_ARCH:=x86_64 aarch64_cortex-a53
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/owxbyz
META_WEBSITE:=https://yz.iepose.com/?from=istore

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
