# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=0.0.1
PKG_RELEASE:=1
META_TITLE:=Nginx
META_TITLE.en:=Nginx
META_DEPENDS:=+luci-nginxer
META_DESCRIPTION:=nginx服务
META_DESCRIPTION.en:=nginx server
META_AUTHOR:=nginx/Carseason
META_ARCH:=x86_64 aarch64_cortex-a53
META_TAGS:=system
META_WEBSITE:=https://nginx.org/en/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
