# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=Nastools
META_DEPENDS:=+luci-i18n-nastools-zh-cn +luci-app-nastools
META_DESCRIPTION:=NAS媒体库资源归集、整理自动化工具
META_DESCRIPTION.en:=NAS media library resource collection and collation automation tool
META_AUTHOR:=jxxghp
META_TAGS:=net service
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/nastools
META_WEBSITE:=https://github.com/jxxghp/nas-tools

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
