# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=NasTools
META_TITLE.en:=NasTools
META_DEPENDS:=+luci-i18n-nastools-zh-cn +nastools +luci-app-nastools
META_DESCRIPTION:=NAS媒体库资源归集、整理自动化工具。
META_DESCRIPTION.en:=NasTools is a tools for resource aggregation running in NAS.access homepage.
META_AUTHOR:=jxxghp
META_ARCH:=x86_64 aarch64_cortex-a53
META_TAGS:=tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/nastools/pages
META_WEBSITE:=https://github.com/jxxghp/nas-tools

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
