include $(TOPDIR)/rules.mk

PKG_VERSION:=1.9.0
PKG_RELEASE:=1
META_TITLE:=贝锐蒲公英
META_TITLE.en:=贝锐蒲公英
META_DEPENDS:=+pgyvpn +lua-md5 +luci-app-pgyvpn
META_DESCRIPTION:=贝锐蒲公英SD-WAN，为个人和企业用户提供简单、安全、稳定、灵活的异地组网方案。让用户不受地域及公网IP限制，快速组建异地虚拟局域网络，打破信息传输壁垒，解决数据远程互访的难题。
META_DESCRIPTION.en:=贝锐蒲公英SD-WAN，为个人和企业用户提供简单、安全、稳定、灵活的异地组网方案。让用户不受地域及公网IP限制，快速组建异地虚拟局域网络，打破信息传输壁垒，解决数据远程互访的难题。
META_AUTHOR:=Oray
META_ARCH:=x86_64
META_TAGS:=networking service
META_LUCI_ENTRY:=/cgi-bin/luci/admin/vpn/pgyvpn
META_WEBSITE:=https://pgy.oray.com

include ../../meta.mk

