# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.5
PKG_RELEASE:=4
META_TITLE:=迅雷快鸟
META_DEPENDS:=+luci-app-xlnetacc
META_DESCRIPTION:=上网提速工具
META_AUTHOR:=Sense <sensec@gmail.com>
META_TAGS:=network tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/xlnetacc
META_WEBSITE:=https://k.xunlei.com/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
