# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.10.0
PKG_RELEASE:=1
META_TITLE:=影牛牛
META_DEPENDS:=+ynn-nas-client +luci-app-ynn-nas-client +luci-i18n-ynn-nas-client-zh-cn
META_DESCRIPTION:=影牛牛臻享影院致力于提供全面的杜比全景声及DTS沉浸声音效超清影视内容，满足高端家庭用户观影需求，是国内家庭影院视频服务平台。内容涵盖国内外院线大片，全网同步上线。支持arm64平台。
META_AUTHOR:=ynn
META_TAGS:=nas tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/nas/ynnnas
META_WEBSITE:=https://www.movienn.com/
META_ARCH:=aarch64

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature