# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=20210426
PKG_RELEASE:=1
META_TITLE:=uHTTPd
META_DEPENDS:=+luci-app-uhttpd +luci-i18n-uhttpd-zh-cn
META_DESCRIPTION:=uHTTPd服务配置
META_AUTHOR:=Daniel Dickinson <openwrt@daniel.thecshore.com>
META_TAGS:=net service
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/uhttpd
META_WEBSITE:=https://github.com/openwrt/luci/tree/master/applications/luci-app-uhttpd

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
