# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.3.3
PKG_RELEASE:=2
META_TITLE:=DDNSTO路由远程
META_DEPENDS:=+ddnsto +luci-app-ddnsto +luci-i18n-ddnsto-zh-cn
META_DESCRIPTION:=DDNS.TO内网穿透，可以外网远程你的路由器
META_AUTHOR:=xiaobao
META_ARCH:=x86_64 aarch64_cortex-a53
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/ddnsto
META_WEBSITE:=https://www.ddnsto.com/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
