# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=Home Assistant
META_DEPENDS:=+luci-app-homeassistant +luci-i18n-homeassistant-zh-cn
META_DESCRIPTION:=开源智能家居系统，将本地控制和隐私放在首位。
META_AUTHOR:=Home Assistant
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/homeassistant
META_WEBSITE:=https://www.home-assistant.io/
META_TUTORIAL:=https://doc.linkease.com/zh/guide/easepi/advanced.html\#home-assistant

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
