# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=homeassistant
META_DEPENDS:=+luci-app-homeassistant +luci-i18n-homeassistant-zh-cn
META_DESCRIPTION:=Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts.
META_AUTHOR:=homeassistant
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/homeassistant
META_WEBSITE:=https://www.home-assistant.io/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
