# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=0.5
PKG_RELEASE:=13
META_TITLE:=Docker Manager
META_DEPENDS:=+luci-app-dockerman +luci-i18n-dockerman-zh-cn +dockerd
META_DESCRIPTION:=管理Docker镜像的Openwrt插件
META_AUTHOR:=lisaac
META_TAGS:=docker tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/docker
META_WEBSITE:=https://github.com/lisaac/luci-app-dockerman

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
