# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=nextcloud
META_DEPENDS:=+luci-app-nextcloud +luci-i18n-nextcloud-zh-cn
META_DESCRIPTION:=A safe home for all your data. Access & share your files, calendars, contacts, mail & more from any device, on your terms 
META_AUTHOR:=nextcloud
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/nextcloud
META_WEBSITE:=https://nextcloud.com/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
