# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221114
META_TITLE:=PhotoPrism相册管理
META_TITLE.en:=PhotoPrism
META_DEPENDS:=+luci-app-photoprism +luci-i18n-photoprism-zh-cn +docker-deps
META_DESCRIPTION:=PhotoPrism是一个AI驱动的相册管理应用。
META_DESCRIPTION.en:=PhotoPrism is an AI-driven photo album management application.
META_AUTHOR:=PhotoPrism
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/photoprism
META_WEBSITE:=https://photoprism.app/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
