# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2
PKG_RELEASE:=20230619
META_TITLE:=开发工具集
META_TITLE.en:=IT-Tools
META_DEPENDS:=+luci-app-ittools +luci-i18n-ittools-zh-cn +docker-deps
META_DESCRIPTION:=开发工具集是集成了很多有用的网页工具。
META_DESCRIPTION.en:=ITTools is useful tools for developer and people working in IT.
META_AUTHOR:=ittools
META_TAGS:=net
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/ittools
META_WEBSITE:=https://it-tools.tech/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
