# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2
PKG_RELEASE:=20230619
META_TITLE:=Unifi控制器
META_TITLE.en:=UnifiController
META_DEPENDS:=+luci-app-unifi +luci-i18n-unifi-zh-cn +docker-deps
META_DESCRIPTION:=Ubnt AC 控制器。
META_DESCRIPTION.en:=Ubnt AC iController.
META_AUTHOR:=Ubiquiti Inc
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/unifi
META_WEBSITE:=https://www.ui.com/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
