# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=KMS服务器
META_DEPENDS:=+luci-i18n-vlmcsd-zh-cn +luci-app-vlmcsd +vlmcsd
META_DESCRIPTION:=KMS服务器可用于激活Windows或Office
META_AUTHOR:=LuCI Team
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/vlmcsd
META_WEBSITE:=https://github.com/coolsnowwolf/luci/tree/master/applications/luci-app-vlmcsd

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
