# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20230615
META_TITLE:=蓝山云 - 流量宝
META_DEPENDS:=+luci-app-bmtedge +luci-i18n-bmtedge-zh-cn +docker-deps
META_DESCRIPTION:=蓝山云-流量宝由蓝山联合金山云推出的一款镜像软件，通过简单安装后可快速加入蓝山的边缘计算生态，在线共享带宽即可赚钱，每月可获取一定的现金回报！
META_AUTHOR:=蓝山云
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/bmtedge
META_WEBSITE:=https://www.bmtcloud.com.cn/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
