# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.1
PKG_RELEASE:=20220217
META_TITLE:=Ubuntu
META_DEPENDS:=+luci-app-ubuntu +luci-i18n-ubuntu-zh-cn
META_DESCRIPTION:=Linkease-PC是为EasePi定制的一套Ubuntu系统。纯英文系统，欢迎各位极客玩家享用。 
META_AUTHOR:=xiaobao
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/ubuntu
META_WEBSITE:=https://www.koolcenter.com/category/apps/?tag=ubuntu

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
