include $(TOPDIR)/rules.mk

PKG_VERSION:=2.0.4
PKG_RELEASE:=1
META_TITLE:=BeeconMini-自组网
META_DEPENDS:=+bxplug
META_ARCH:=x86_64 aarch64
META_DESCRIPTION:=BeeconMini开发的一款可以在X86/ARM路由里管理自组网AP的控制插件，并提供X86/ARM路由下的全屋Wi-Fi组网方案。
META_AUTHOR:=BeeconMini
META_TAGS:=net networking
META_LUCI_ENTRY:=/cgi-bin/luci/admin/beeconmini
META_WEBSITE:=http://www.beeconx.com.cn/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
