# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=0.5.5.0
PKG_RELEASE:=1
META_TITLE:=istorex
META_TITLE.en:=istorex
META_DEPENDS:=+luci-app-istorex
META_DESCRIPTION:=为iStoreOS适配的全新首页。
META_DESCRIPTION.en:=A new homepage for iStoreOS.
META_AUTHOR:=Carseason
META_ARCH:=x86_64 aarch64_cortex-a53
META_TAGS:=net system
META_LUCI_ENTRY:=/cgi-bin/luci/admin/istorex
META_WEBSITE:=https://github.com/linkease/nas-packages-luci

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
