# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221213
META_TITLE:=Xteve
META_TITLE.en:=Xteve
META_DEPENDS:=+luci-app-xteve +luci-i18n-xteve-zh-cn +docker-deps
META_DESCRIPTION:=Xteve是一个在线电视源的代理工具。
META_DESCRIPTION.en:=Xteve is a proxy tool for online TV sources.
META_AUTHOR:=xteve-project
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/xteve
META_WEBSITE:=https://github.com/xteve-project/xTeVe
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
