# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0
PKG_RELEASE:=1
META_TITLE:=MAC克隆
META_TITLE.en:=MAC Clone
META_DEPENDS:=+luci-app-mac +luci-i18n-mac-zh-cn
META_DESCRIPTION:=克隆Wan口MAC地址。
META_DESCRIPTION.en:=Clone Wan port MAC address.
META_AUTHOR:=Twinzo1
META_TAGS:=system tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/network/mac
META_WEBSITE:=https://github.com/Twinzo1/openwrt/tree/master/luci-app-mac

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
