# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=xunyou
META_DEPENDS:=+luci-app-xunyou +luci-i18n-xunyou-zh-cn
META_DESCRIPTION:=迅游是一款小巧且功能强大的网游加速器，下载仅需10秒左右，一键快捷安装，全面兼容win10在内的所有windows系统。迅游所采用的第五代网游加速技术能更有效地为您解决网游卡机、掉线、延时高、登录难等问题
META_AUTHOR:=xunyou
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/xunyou
META_WEBSITE:=https://www.xunyou.com/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
