# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=qBittorrent
META_DEPENDS:=+qBittorrent-static +luci-app-qbittorrent +luci-i18n-qbittorrent-zh-cn
META_DESCRIPTION:=专业磁力种子下载工具。
META_AUTHOR:=The qBittorrent project 
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/nas/qBittorrent
META_WEBSITE:=https://www.qbittorrent.org/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
