# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.1.0
PKG_RELEASE:=20211203
META_TITLE:=可道云
META_DEPENDS:=+luci-app-kodexplorer +luci-i18n-kodexplorer-zh-cn
META_DESCRIPTION:=一款快捷高效的私有云和在线文档管理系统，为个人网站、企业私有云部署、网络存储、在线文档管理、在线办公等提供安全可控，简便易用、可高度定制的私有云产品。采用windows风格界面、操作习惯，无需适应即可快速上手，支持几百种常用文件格式的在线预览，可扩展易定制。 
META_AUTHOR:=kodexplorer
META_TAGS:=nas service
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/kodexplorer
META_WEBSITE:=https://kodcloud.com

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
