# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=3.7.4
PKG_RELEASE:=2
META_TITLE:=BaiduPCS-Web
META_DEPENDS:=+baidupcs-web +luci-app-baidupcs-web
META_DESCRIPTION:=基于BaiduPCS-Go, 可以让你高效的使用百度云。
META_AUTHOR:=Erope/KFERMercer
META_ARCH:=x86_64 aarch64_cortex-a53
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/nas/baidupcs-web
META_WEBSITE:=https://github.com/Erope/BaiduPCS-Go

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
