# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=adguardhome
META_DEPENDS:=+luci-app-adguardhome
META_DESCRIPTION:=免费和开源、强大的全网广告和跟踪器阻止 DNS 服务器
META_AUTHOR:=AdGuard
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/AdGuardHome
META_WEBSITE:=https://github.com/AdguardTeam/AdGuardHome

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
