# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=2.2
PKG_RELEASE:=2
META_TITLE:=多账号多拨
META_DEPENDS:=+mwan3-deps +luci-app-multiaccountdial
META_DESCRIPTION:=支持多账号的多拨插件
META_AUTHOR:=xiaobao
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/network/multiaccountdial
META_WEBSITE:=https://github.com/linkease/openwrt-app-actions/tree/main/applications/luci-app-multiaccountdial

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
