# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2
PKG_RELEASE:=20230412
META_TITLE:=Memos知识管理
META_TITLE.en:=Memos
META_DEPENDS:=+luci-app-memos +luci-i18n-memos-zh-cn +docker-deps
META_DESCRIPTION:=开源的极简的碎片化知识管理工具。
META_DESCRIPTION.en:=Open source minimalist fragmented knowledge management tool.
META_AUTHOR:=usememos
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/memos
META_WEBSITE:=https://usememos.com/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
