# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=0.0.8
PKG_RELEASE:=1
META_TITLE:=MFUN
META_DEPENDS:=+luci-app-mfun +luci-i18n-mfun-zh-cn
META_DESCRIPTION:=轻量的影音媒体库
META_DESCRIPTION.en:=Mfun is an multimedia program.
META_AUTHOR:=Carseason
META_ARCH:=x86_64 aarch64
META_TAGS:=nas multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/mfun
META_WEBSITE:=https://www.mfun.cloud

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
