# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221212
META_TITLE:=DrawIO绘图
META_TITLE.en:=DrawIO
META_DEPENDS:=+luci-app-drawio +luci-i18n-drawio-zh-cn +docker-deps
META_DESCRIPTION:=DrawIO是运行在浏览器中的在线绘图工具。
META_DESCRIPTION.en:=DrawIO is an online drawing tool that runs in the browser.
META_AUTHOR:=diagrams.net
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/drawio
META_WEBSITE:=https://www.diagrams.net/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
