# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=Heimdall
META_DEPENDS:=+luci-i18n-heimdall-zh-cn +luci-app-heimdall
META_DESCRIPTION:=Heimdall 应用程序仪表板是所有 Web 应用程序的仪表板。不过，它不需要仅限于应用程序，您可以添加任何您喜欢的链接
META_DESCRIPTION.en:=Heimdall Application Dashboard is a dashboard for all your web applications. It doesn't need to be limited to applications though, you can add links to anything you like.
META_AUTHOR:=LinuxServer.io
META_TAGS:=net service
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/heimdall
META_WEBSITE:=https://heimdall.site/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
