# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.1
PKG_RELEASE:=20240117
META_TITLE:=CloudDrive2
META_DEPENDS:=+luci-app-clouddrive2 +luci-i18n-clouddrive2-zh-cn +docker-deps
META_DESCRIPTION:=CloudDrive 是一个强大的多云盘管理工具，为用户提供包含云盘本地挂载的一站式的多云盘解决方案。
META_DESCRIPTION.en:=CloudDrive is a powerful multi-cloud drive management tool with local mounting of cloud drives.
META_AUTHOR:=CloudDrive/jjm2473
META_TAGS:=service tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/clouddrive2
META_WEBSITE:=https://www.clouddrive2.com/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
