# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=3.12
PKG_RELEASE:=10
META_TITLE:=全能推送PushBot
META_DEPENDS:=+luci-app-pushbot
META_DESCRIPTION:=用于OpenWRT/LEDE路由器上进行微信/Telegram/钉钉/飞书/推送的插件
META_AUTHOR:=tty228/zzsj0928
META_TAGS:=service monitor
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/pushbot
META_WEBSITE:=https://github.com/zzsj0928/luci-app-pushbot

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
