# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221114
META_TITLE:=Penpot设计平台
META_TITLE.en:=Penpot
META_DEPENDS:=+luci-app-penpot +luci-i18n-penpot-zh-cn +docker-deps
META_DESCRIPTION:=Penpot是第一个开源的便于团队协作的在线设计平台。
META_DESCRIPTION.en:=Penpot is the first open source online design platform for team collaboration.
META_AUTHOR:=Kaleidos
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/penpot
META_WEBSITE:=https://penpot.app/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
