# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221114
META_TITLE:=ChineseSubFinder中文字幕
META_TITLE.en:=ChineseSubFinder
META_DEPENDS:=+luci-app-chinesesubfinder +luci-i18n-chinesesubfinder-zh-cn +docker-deps
META_DESCRIPTION:=ChineseSubFinder是一个中文字幕平台。
META_DESCRIPTION.en:=ChineseSubFinder is a Chinese subtitle platform.
META_AUTHOR:=ChineseSubFinder
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/chinesesubfinder
META_WEBSITE:=https://github.com/allanpk716/ChineseSubFinder
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
