# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221106
META_TITLE:=Plex影院
META_TITLE.en:=Plex
META_DEPENDS:=+luci-app-plex +luci-i18n-plex-zh-cn +docker-deps
META_DESCRIPTION:=Plex是一个多媒体串流平台，可以让您方便地管理和串流您的媒体。
META_DESCRIPTION.en:=Plex is the volunteer-built media solution that puts you in control of your media.
META_AUTHOR:=Plex
META_TAGS:=net multimedia
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/plex
META_WEBSITE:=https://www.plex.tv/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
