# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=5
META_TITLE:=酷友社KAI
META_TITLE.en:=kai
META_DEPENDS:=+luci-app-kai +kai +kai_session
META_DESCRIPTION:=KAI安装软件助手(iStoreOS 24版本以上适用)
META_DESCRIPTION.en:=AI software installation assistant
META_AUTHOR:=koolcenter
META_ARCH:=x86_64 aarch64
META_TAGS:=system ai
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/kai
META_WEBSITE:=https://www.koolcenter.com

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
