include $(TOPDIR)/rules.mk

PKG_VERSION:=4.0.6
PKG_RELEASE:=20260107
META_TITLE:=节点小宝-远程助手
META_DEPENDS:=+owjdxb
META_DESCRIPTION:=多设备P2P直连，不限速互通。【组网互通】组网IP互访，跨设备挂载Samba、WebDAV等；【智能中转】转发本地设备，即可访问异地局域网内设备；【安全加密】全程端到端加密，数据传输无忧。
META_AUTHOR:=TopwayNetwork
META_TAGS:=net tool
META_ARCH:=x86_64 aarch64
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/owjdxb
META_WEBSITE:=https://www.iepose.com/?from=istore
META_TUTORIAL:=https://www.iepose.com/service?from=istore

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
