# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1
PKG_RELEASE:=3
META_TITLE:=ARP Binding
META_DEPENDS:=+luci-app-arpbind +luci-i18n-arpbind-zh-cn
META_DESCRIPTION:=IP/MAC绑定
META_AUTHOR:=LuCI Team
META_TAGS:=docker tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/network/arpbind
META_WEBSITE:=https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-arpbind

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
