# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2
PKG_RELEASE:=20220628
META_TITLE:=网心云
META_DEPENDS:=+luci-app-wxedge +luci-i18n-wxedge-zh-cn
META_DESCRIPTION:=「容器魔方」由网心云推出的一款docker容器镜像软件，通过简单安装后即可快速加入网心云共享计算生态网络，为网心科技星域云贡献带宽和存储资源，用户根据每日的贡献量可获得相应的现金收益回报。 
META_AUTHOR:=网心云
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/wxedge
META_WEBSITE:=https://www.onethingcloud.com/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
