# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=2
META_TITLE:=IP限速
META_DEPENDS:=+luci-app-eqos +luci-i18n-eqos-zh-cn
META_DESCRIPTION:=简单的IP限速控制服务
META_AUTHOR:=Jianhui Zhao
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/network/eqos
META_WEBSITE:=https://github.com/kiddin9

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
