# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=5.1.6
PKG_RELEASE:=1
META_TITLE:=星空组网
META_TITLE.en:=StarVPN
META_DEPENDS:=+starvpn +luci-app-starvpn
META_DESCRIPTION:=轻松实现内网穿透，打造虚拟局域网！这款简单易用的国货工具，不仅保障数据安全，更以高效传输著称。由10年互联网老兵倾心打造，让您轻松享受网络连接的便利！
META_DESCRIPTION.en:=Easily achieve internal network penetration and create a virtual LAN! This simple and easy-to-use domestic tool not only ensures data security, but is also known for efficient transmission. Created by 10 years of Internet veterans, you can easily enjoy the convenience of network connection!
META_AUTHOR:=LD <zhangxianwei@mail.starvpn.cn>
META_TAGS:=networking service
META_LUCI_ENTRY:=/cgi-bin/luci/admin/starvpn
META_WEBSITE:=https://starvpn.cn/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
