# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=20210426
PKG_RELEASE:=1
META_TITLE:=灵缇加速器
META_DEPENDS:=+luci-app-LingTiGameAcc
META_DESCRIPTION:=灵缇游戏加速器
META_AUTHOR:=eSir Playground
META_TAGS:=network tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/lingti
META_WEBSITE:=https://www.lingti.com/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
