# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2
PKG_RELEASE:=20240524
META_TITLE:=MTPhotos相册
META_TITLE.en:=MTPhotos
META_DEPENDS:=+luci-app-mtphotos +luci-i18n-mtphotos-zh-cn +docker-deps
META_DESCRIPTION:=MTPhotos是一款简单、好用的照片管理系统。
META_DESCRIPTION.en:=MTPhotos is simple and easy-to-use photo management system.
META_AUTHOR:=MTPhotos
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/mtphotos
META_WEBSITE:=https://mtmt.tech/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
