# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221117
META_TITLE:=迅雷下载
META_TITLE.en:=Xunlei
META_DEPENDS:=+luci-app-xunlei +luci-i18n-xunlei-zh-cn +docker-deps
META_DESCRIPTION:=Xunlei是一个下载工具。
META_DESCRIPTION.en:=Xunlei is a download tool.
META_AUTHOR:=xunlei
META_TAGS:=download tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/xunlei
META_WEBSITE:=https://www.xunlei.com/
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
