# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=PassWall
META_DEPENDS:=+luci-app-passwall +luci-i18n-passwall-zh-cn
META_DESCRIPTION:=让你更高效的上网，可正常访问全部网络
META_AUTHOR:=kenzok8
META_ARCH:=x86_64
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/passwall
META_WEBSITE:=https://github.com/kenzok8

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
