# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=分流助手
META_DEPENDS:=+luci-app-arpbind +luci-i18n-arpbind-zh-cn
META_DESCRIPTION:=分流助手可以支持多根网线或者多个PPPOE账号的同时拨号使用和负载均衡。
META_AUTHOR:=LuCI Team
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/network/mwan
META_WEBSITE:=https://github.com/openwrt/luci/tree/openwrt-21.02/applications/luci-app-mwan3

include ../../meta.mk

