# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.1.0
PKG_RELEASE:=4
META_TITLE:=nps
META_DEPENDS:=+luci-app-nps +luci-i18n-nps-zh-cn
META_DESCRIPTION:=一款轻量级、功能强大的内网穿透代理服务器。
META_AUTHOR:=LuCI Team
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/nps
META_WEBSITE:=https://github.com/ehang-io/nps

include ../../meta.mk
