# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.4.1
PKG_RELEASE:=4
META_TITLE:=Rclone
META_DEPENDS:=+rclone +rclone-ng +rclone-webui-react +luci-app-rclone +luci-i18n-rclone-zh-cn
META_DESCRIPTION:=Rclone是一个用于同步云平台文件和目录的工具
META_AUTHOR:=Rclone Contributors/ElonH
META_TAGS:=service tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/nas/rclone
META_WEBSITE:=https://rclone.org/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
