# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221106
META_TITLE:=MyMind思维导图
META_TITLE.en:=MyMind
META_DEPENDS:=+luci-app-mymind +luci-i18n-mymind-zh-cn +docker-deps
META_DESCRIPTION:=MyMind 是一个在线思维导图编辑器。
META_DESCRIPTION.en:=MyMind is an online mind map editor.
META_AUTHOR:=MyMind
META_TAGS:=net tool
META_LUCI_ENTRY:=/cgi-bin/luci/admin/services/mymind
META_WEBSITE:=https://github.com/ondras/my-mind
META_TUTORIAL:=

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
