# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
META_TITLE:=NetData系统监控
META_DEPENDS:=+netdata +luci-app-netdata +luci-i18n-netdata-zh-cn
META_DESCRIPTION:=一眼掌握机器运行状态/系统效能关键指标
META_AUTHOR:=netdata
META_TAGS:=system monitor
META_LUCI_ENTRY:=/cgi-bin/luci/admin/status/netdata
META_WEBSITE:=https://www.netdata.cloud/

include ../../meta.mk

# call BuildPackage - OpenWrt buildroot signature
